---
swagger: "2.0"
info:
  description: "virtual door application visitor portal"
  version: "1.0.0"
  title: "door_visitor_api"
host: "ch4cjufjdb.execute-api.us-east-1.amazonaws.com"
basePath: "/v1"
schemes:
- "https"
paths:
  /virtual_door:
    post:
      operationId: "sendMessage"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "VisitorRequest"
        required: true
        schema:
          $ref: "#/definitions/VisitorRequest"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/VisitorResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        500:
          description: "500 response"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "403 response"
          schema:
            $ref: "#/definitions/Error"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
definitions:
  Message:
    type: "object"
    properties:
      type:
        type: "string"
      unstructured:
        $ref: "#/definitions/UnstructuredMessage"
  UnstructuredMessage:
    type: "object"
    properties:
      user_id:
        type: "string"
      passcode:
        type: "string"
      valid:
        type: "string"
      name:
        type: "string"
      timestamp:
        type: "string"
        format: "datetime"
  VisitorResponse:
    type: "object"
    properties:
      messages:
        type: "array"
        items:
          $ref: "#/definitions/Message"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  VisitorRequest:
    type: "object"
    properties:
      messages:
        type: "array"
        items:
          $ref: "#/definitions/Message"
